version: 0.2
phases:
  install:
    # flutterモジュールのpubspec.yamlからバージョンを取得するために
    # yqコマンドをインストールする
    commands:
      - apt update
      - apt install -y gnupg2
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
      - add-apt-repository -y ppa:rmescandon/yq
      - apt install yq -y
  build:
    # AARを作成する
    commands:
      - flutter build aar --build-number `yq r pubspec.yaml version`
artifacts:
  # アーティファクトとしてS3にコピーするディレクトリを指定する
  files:
    - '**/*'
  base-directory: build/host/outputs/repo
